### ISSUE TITLE
Importing MultipleComponents or MultipleComponentsList raises SyntaxError

### ISSUE THREAD

**Issue by nickybaby** [lob/lob-python#203]
![image](https://github.com/lob/lob-python/assets/4712129/e114f5aa-ce57-49e0-8968-66dbe648b1cd)

`from lob_python.models import MultipleComponentsList
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nick/Code/lob/lob-python/lob_python/models/__init__.py", line 44, in <module>
    from lob_python.model.campaign import Campaign
  File "/home/nick/Code/lob/lob-python/lob_python/model/campaign.py", line 32, in <module>
    from lob_python.model.campaign_creative import CampaignCreative
  File "/home/nick/Code/lob/lob-python/lob_python/model/campaign_creative.py", line 110
    'details': (, PostcardDetailsWritable, type(None)),  # noqa: E501
             ^
SyntaxError: expression expected after dictionary key and ':'`

`from lob_python.models import MultipleComponents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nick/Code/lob/lob-python/lob_python/models/__init__.py", line 44, in <module>
    from lob_python.model.campaign import Campaign
  File "/home/nick/Code/lob/lob-python/lob_python/model/campaign.py", line 32, in <module>
    from lob_python.model.campaign_creative import CampaignCreative
  File "/home/nick/Code/lob/lob-python/lob_python/model/campaign_creative.py", line 110
    'details': (, PostcardDetailsWritable, type(None)),  # noqa: E501`

This dict is autogenerated from OpenAPI, but also if you refactor the code, a circular import appears:

![image](https://github.com/lob/lob-python/assets/4712129/4ae9f64a-4938-4ff0-ae71-99f6876556d6)

**Comment by ryancausey** [comment]
I am still getting this error in lob-python version 5.1.1. Is there a fix planned or is it blocked on upstream changes to the Open API generator?
